/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://bchloo7hmfhgngdvsjcy3pmth4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-q7inxsawlrh3domqzse3mirroi",
    "aws_cloud_logic_custom": [
        {
            "name": "expoeas",
            "endpoint": "https://al0i164sq4.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-1:24a647fa-34fc-495b-8064-8d2ec40623c1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_9J55GhYs9",
    "aws_user_pools_web_client_id": "h4jn0os7aujfnhbmqu6m0ufvl",
    "oauth": {
        "domain": "expoeas-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "exp://127.0.0.1:19000/",
        "redirectSignOut": "exp://127.0.0.1:19000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_AND_IDENTITY_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "GOOGLE",
        "APPLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "expoapp191130-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
